import Head from "next/head";
import Image from "next/image";
import devtrav from "public/dev-trav-wave.png";
import {FiFeather} from "react-icons/fi"
import {
  FaStrava,
  FaInstagram,
  FaGithub,
  FaTwitter,
  FaLinkedin,
} from "react-icons/fa";

export default function Home() {
  return (
    <div>
      <Head>
        <title>FinTechTrav</title>
        <meta name="description" content="Generated by Travis Keefe" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-gray-900 px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            {/* <div>
              <ul className="flex justify-center gap-16 py-3">
                <li>
                  <a
                    className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8"
                    href="#"
                  >
                    Contact Me
                  </a>
                </li>
              </ul>
            </div> */}
          </nav>
          <div className="text-center p-10">
            <h2 className="text-5xl py-2 text-teal-600 font-large">
              Travis Keefe
            </h2>
            <h3 className="text-2xl py-2">
              Runner by morning, software engineer by day, and finance
              enthusiast by night.
            </h3>
          </div>
          <div className="text-5xl text-teal-600 flex justify-center gap-16 py-2">
            <a href="https://www.instagram.com/trav.keefe/">
              <FaInstagram />
            </a>
            <a href="https://twitter.com/FinTechTrav">
              <FaTwitter />
            </a>
            <a href="https://github.com/tkeefe">
              <FaGithub />
            </a>
            <a href="https://www.linkedin.com/in/travis-keefe-969901132/">
              <FaLinkedin />
            </a>
            <a href="https://www.strava.com/athletes/15260121">
              <FaStrava />
            </a>
            <a href="https://join.robinhood.com/travisk175">
              <FiFeather />
            </a>
          </div>

          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden">
            <Image src={devtrav} layout="fill" objectFit="cover" />
          </div>
        </section>
      </main>
    </div>
  );
}
